name: Andrew Love
favicon: null
layout_spectrum: 0.98557
typography_spectrum: 0.50264
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbebae'
    - '#bec5cb'
    - '#787e8c'
    - '#10100e'
    - '#634f2a'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
